source "http://rubygems.org"

# Declare your gem's dependencies in lk.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
gem 'jquery-rails'
gem 'composite_primary_keys', '~> 4.0.0'
gem 'pdfkit'
gem 'writeexcel'
#gem 'gift-core', :git => "git@github.com:rilya/giftb2b.git"
gem 'gift-core', :path => "~/ROR/work/gift/core"
gem 'gift-base', :path => "~/ROR/work/gift/base"
gem 'gift-auth', :path => "~/ROR/work/gift/auth"
gem 'paperclip'   
gem "mysql2"
